//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_UserProfiles
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAccessRequest { get; set; }
        public string AccessRightRequest { get; set; }
        public string TimeZoneCode { get; set; }
        public Nullable<bool> TermsAccepted { get; set; }
        public Nullable<System.DateTime> TermsAcceptedDateTime { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
