//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_Permissions
    {
        public tblIdentity_Permissions()
        {
            this.tblIdentity_UserSystemRoles = new HashSet<tblIdentity_UserSystemRoles>();
            this.tblIdentity_SystemRolePermissions = new HashSet<tblIdentity_SystemRolePermissions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<tblIdentity_UserSystemRoles> tblIdentity_UserSystemRoles { get; set; }
        public virtual ICollection<tblIdentity_SystemRolePermissions> tblIdentity_SystemRolePermissions { get; set; }
    }
}
