//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_Gateways
    {
        public tblIdentity_Gateways()
        {
            this.tblIdentity_UserSystemRoles = new HashSet<tblIdentity_UserSystemRoles>();
            this.tblIdentity_GatewaySystemRoles = new HashSet<tblIdentity_GatewaySystemRoles>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PortalGatewayID { get; set; }
        public int PortalID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    
        public virtual tblIdentity_Portals tblIdentity_Portals { get; set; }
        public virtual ICollection<tblIdentity_UserSystemRoles> tblIdentity_UserSystemRoles { get; set; }
        public virtual ICollection<tblIdentity_GatewaySystemRoles> tblIdentity_GatewaySystemRoles { get; set; }
    }
}
