//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_Portals
    {
        public tblIdentity_Portals()
        {
            this.tblIdentity_Gateways = new HashSet<tblIdentity_Gateways>();
            this.tblIdentity_PasswordPolicies = new HashSet<tblIdentity_PasswordPolicies>();
            this.tblIdentity_UserAssets = new HashSet<tblIdentity_UserAssets>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> PortalPortalID { get; set; }
        public string DomainURLs { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string DatabaseName { get; set; }
    
        public virtual ICollection<tblIdentity_Gateways> tblIdentity_Gateways { get; set; }
        public virtual ICollection<tblIdentity_PasswordPolicies> tblIdentity_PasswordPolicies { get; set; }
        public virtual ICollection<tblIdentity_UserAssets> tblIdentity_UserAssets { get; set; }
    }
}
