//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_UserSystemRoles
    {
        public int UserId { get; set; }
        public int RoleId { get; set; }
        public int GatewayId { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public int PermissionId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tblIdentity_Gateways tblIdentity_Gateways { get; set; }
        public virtual tblIdentity_SystemRoles tblIdentity_SystemRoles { get; set; }
        public virtual tblIdentity_Permissions tblIdentity_Permissions { get; set; }
    }
}
