//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_PasswordPolicies
    {
        public int Id { get; set; }
        public Nullable<int> PortalId { get; set; }
        public Nullable<int> RequiredLength { get; set; }
        public Nullable<bool> RequireNonLetterOrDigit { get; set; }
        public Nullable<bool> RequireDigit { get; set; }
        public Nullable<bool> RequireLowercase { get; set; }
        public Nullable<bool> RequireUppercase { get; set; }
    
        public virtual tblIdentity_Portals tblIdentity_Portals { get; set; }
    }
}
