//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JMM.APEC.Identity.DataObjects.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIdentity_SystemRolePermissions
    {
        public int SystemRoleId { get; set; }
        public int PermissionId { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
    
        public virtual tblIdentity_Permissions tblIdentity_Permissions { get; set; }
        public virtual tblIdentity_SystemRoles tblIdentity_SystemRoles { get; set; }
    }
}
